-- Add upsell trigger table for free-credit threshold events.

BEGIN;

CREATE TABLE IF NOT EXISTS public.upsell_triggers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id text NOT NULL,
  trigger_type text NOT NULL DEFAULT 'free-credits-50%',
  shown_at timestamptz,
  converted boolean NOT NULL DEFAULT false,
  trigger_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT upsell_triggers_user_type_uq UNIQUE (user_id, trigger_type)
);

CREATE INDEX IF NOT EXISTS upsell_triggers_user_idx
  ON public.upsell_triggers (user_id);

CREATE OR REPLACE FUNCTION public.mark_upsell_trigger_if_needed(p_user_id text, p_call_count integer)
RETURNS boolean
LANGUAGE plpgsql
AS $$
BEGIN
  IF p_call_count = 5 THEN
    INSERT INTO public.upsell_triggers (user_id, trigger_type, shown_at, trigger_payload)
    VALUES (p_user_id, 'free-credits-50%', now(), jsonb_build_object('call_count', p_call_count, 'threshold', 5))
    ON CONFLICT (user_id, trigger_type) DO NOTHING;

    RETURN TRUE;
  END IF;

  RETURN FALSE;
END;
$$;

COMMIT;
