-- Add referral storage and lifecycle for conversion rewards.

BEGIN;

CREATE TABLE IF NOT EXISTS public.referral_codes (
  code text PRIMARY KEY,
  owner_id text NOT NULL,
  uses integer NOT NULL DEFAULT 0,
  credits_awarded integer NOT NULL DEFAULT 0,
  used_by text[] NOT NULL DEFAULT '{}'::text[],
  last_used_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS referral_codes_owner_idx
  ON public.referral_codes (owner_id);

CREATE UNIQUE INDEX IF NOT EXISTS referral_codes_code_uq
  ON public.referral_codes (code);

CREATE TABLE IF NOT EXISTS public.referral_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  referral_code text NOT NULL REFERENCES public.referral_codes(code) ON DELETE CASCADE,
  new_user_id text NOT NULL,
  event_type text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE UNIQUE INDEX IF NOT EXISTS referral_events_referral_user_uq
  ON public.referral_events (referral_code, new_user_id)
  WHERE event_type = 'referral_conversion';

COMMIT;
