-- Add tiered pricing model and helper function.
-- Issue: #1 — implement revenue tiering after free credits.

BEGIN;

CREATE TABLE IF NOT EXISTS public.pricing_tiers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tier_code text NOT NULL CHECK (tier_code IN ('free', 'standard', 'premium', 'priority')),
  min_calls integer NOT NULL,
  max_calls integer,
  price_per_call_usd numeric(10,4) NOT NULL,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT pricing_tiers_range_chk CHECK (max_calls IS NULL OR max_calls > min_calls)
);

CREATE INDEX IF NOT EXISTS pricing_tiers_range_idx
  ON public.pricing_tiers (tier_code);

INSERT INTO public.pricing_tiers (tier_code, min_calls, max_calls, price_per_call_usd, notes)
VALUES
  ('free', 0, 50, 0.0000, 'First 50 calls are free'),
  ('standard', 50, 500, 0.0100, 'Standard price band'),
  ('premium', 500, NULL, 0.0300, 'Premium volume band'),
  ('priority', 0, NULL, 0.1000, 'Priority jobs override volume bands')
ON CONFLICT DO NOTHING;

CREATE OR REPLACE FUNCTION public.get_tier_price(call_count integer, priority_flag boolean)
RETURNS numeric(10,4)
LANGUAGE plpgsql
STABLE
AS $$
DECLARE
  resolved_price numeric(10,4);
BEGIN
  IF call_count IS NULL OR call_count < 0 THEN
    RAISE EXCEPTION 'call_count must be a non-negative integer';
  END IF;

  IF priority_flag THEN
    SELECT price_per_call_usd
      INTO resolved_price
      FROM public.pricing_tiers
     WHERE tier_code = 'priority'
     LIMIT 1;
  ELSIF call_count <= 50 THEN
    SELECT price_per_call_usd
      INTO resolved_price
      FROM public.pricing_tiers
     WHERE tier_code = 'free'
     LIMIT 1;
  ELSIF call_count <= 500 THEN
    SELECT price_per_call_usd
      INTO resolved_price
      FROM public.pricing_tiers
     WHERE tier_code = 'standard'
     LIMIT 1;
  ELSE
    SELECT price_per_call_usd
      INTO resolved_price
      FROM public.pricing_tiers
     WHERE tier_code = 'premium'
     LIMIT 1;
  END IF;

  RETURN resolved_price;
END;
$$;

CREATE OR REPLACE FUNCTION public.get_tier(call_count integer, priority_flag boolean)
RETURNS text
LANGUAGE plpgsql
STABLE
AS $$
BEGIN
  IF call_count IS NULL OR call_count < 0 THEN
    RAISE EXCEPTION 'call_count must be a non-negative integer';
  END IF;

  IF priority_flag THEN
    RETURN 'priority';
  ELSIF call_count <= 50 THEN
    RETURN 'free';
  ELSIF call_count <= 500 THEN
    RETURN 'standard';
  ELSE
    RETURN 'premium';
  END IF;
END;
$$;

COMMIT;
