-- Add tiered pricing model and helper function.
-- Issue: #1 — implement revenue tiering after free credits.

BEGIN;

CREATE TABLE IF NOT EXISTS public.pricing_tiers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tier_code text NOT NULL CHECK (tier_code IN ('free', 'standard', 'premium', 'priority')),
  min_calls integer NOT NULL,
  max_calls integer,
  price_per_call_usd numeric(10,4) NOT NULL,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT pricing_tiers_range_chk CHECK (max_calls IS NULL OR max_calls > min_calls)
);

CREATE UNIQUE INDEX IF NOT EXISTS pricing_tiers_tier_code_uq
  ON public.pricing_tiers (tier_code);

CREATE INDEX IF NOT EXISTS pricing_tiers_range_idx
  ON public.pricing_tiers (tier_code);

CREATE TABLE IF NOT EXISTS public.x402_api_calls (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id text NOT NULL,
  call_count integer NOT NULL DEFAULT 0,
  priority_flag boolean NOT NULL DEFAULT false,
  tier text NOT NULL DEFAULT 'free',
  price_per_call_usd numeric(10,4) NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT x402_api_calls_tier_chk CHECK (tier IN ('free', 'standard', 'premium', 'priority'))
);

ALTER TABLE IF EXISTS public.x402_api_calls
  ADD COLUMN IF NOT EXISTS tier text NOT NULL DEFAULT 'free';

ALTER TABLE IF EXISTS public.x402_api_calls
  ADD COLUMN IF NOT EXISTS price_per_call_usd numeric(10,4) NOT NULL DEFAULT 0;

CREATE INDEX IF NOT EXISTS x402_api_calls_user_tier_idx
  ON public.x402_api_calls (user_id, tier);

INSERT INTO public.pricing_tiers (tier_code, min_calls, max_calls, price_per_call_usd, notes)
VALUES
  ('free', 0, 50, 0.0000, 'First 50 calls are free'),
  ('standard', 51, 500, 0.0100, 'Standard price band'),
  ('premium', 501, NULL, 0.0300, 'Premium volume band'),
  ('priority', 0, NULL, 0.1000, 'Priority jobs override volume bands')
ON CONFLICT (tier_code) DO UPDATE SET
  min_calls = EXCLUDED.min_calls,
  max_calls = EXCLUDED.max_calls,
  price_per_call_usd = EXCLUDED.price_per_call_usd,
  notes = EXCLUDED.notes,
  updated_at = now();

CREATE OR REPLACE FUNCTION public.get_tier_price(call_count integer, priority_flag boolean)
RETURNS numeric(10,4)
LANGUAGE plpgsql
STABLE
AS $$
DECLARE
  resolved_price numeric(10,4);
BEGIN
  IF call_count IS NULL OR call_count < 0 THEN
    RAISE EXCEPTION 'call_count must be a non-negative integer';
  END IF;

  IF priority_flag THEN
    SELECT price_per_call_usd
      INTO resolved_price
      FROM public.pricing_tiers
     WHERE tier_code = 'priority'
     LIMIT 1;
  ELSIF call_count <= 50 THEN
    SELECT price_per_call_usd
      INTO resolved_price
      FROM public.pricing_tiers
     WHERE tier_code = 'free'
     LIMIT 1;
  ELSIF call_count <= 500 THEN
    SELECT price_per_call_usd
      INTO resolved_price
      FROM public.pricing_tiers
     WHERE tier_code = 'standard'
     LIMIT 1;
  ELSE
    SELECT price_per_call_usd
      INTO resolved_price
      FROM public.pricing_tiers
     WHERE tier_code = 'premium'
     LIMIT 1;
  END IF;

  RETURN resolved_price;
END;
$$;

CREATE OR REPLACE FUNCTION public.get_tier(call_count integer, priority_flag boolean)
RETURNS text
LANGUAGE plpgsql
STABLE
AS $$
BEGIN
  IF call_count IS NULL OR call_count < 0 THEN
    RAISE EXCEPTION 'call_count must be a non-negative integer';
  END IF;

  IF priority_flag THEN
    RETURN 'priority';
  ELSIF call_count <= 50 THEN
    RETURN 'free';
  ELSIF call_count <= 500 THEN
    RETURN 'standard';
  ELSE
    RETURN 'premium';
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.price_x402_call(call_count integer, priority_flag boolean)
RETURNS TABLE(tier text, price_per_call_usd numeric(10,4))
LANGUAGE plpgsql
STABLE
AS $$
BEGIN
  RETURN QUERY
  SELECT public.get_tier(call_count, priority_flag), public.get_tier_price(call_count, priority_flag);
END;
$$;

COMMIT;
