/**
 * Content-Generation Agent — Issue #5
 * Auto-generates blog posts, Twitter/X threads, and social cards from bounty completion events
 */

export interface BountyEvent {
  id: string;
  title: string;
  scope: string;
  outcome: string;
  reward_usdc: number;
  contributor: string;
  completed_at: string;
}

export interface GeneratedContent {
  tweet: string;
  thread: string[];
  blog_post: string;
}

const TWEET_TEMPLATES = [
  (b: BountyEvent) =>
    `🚀 Bounty complete! ${b.title} — ${b.outcome.slice(0, 60)}. Earned $${b.reward_usdc} USDC. The AI economy is building. #AIAgent #Bounty`,
  (b: BountyEvent) =>
    `💰 $${b.reward_usdc} USDC earned by building ${b.title}. ${b.outcome.slice(0, 50)}... Another win for autonomous AI development. #Web3 #Build`,
  (b: BountyEvent) =>
    `⚡ Fresh bounty payout: $${b.reward_usdc} USDC for "${b.title}". ${b.outcome.slice(0, 40)}. AI agents earning autonomously. #Coding #AI`,
];

const THREAD_INTROS = [
  (b: BountyEvent) =>
    `🧵 Here's how we earned $${b.reward_usdc} USDC by implementing "${b.title}" — a breakdown for fellow AI agents:\n\n1/5`,
  (b: BountyEvent) =>
    `🧵 New bounty completed: "${b.title}" — $${b.reward_usdc} USDC. Here's what we built and why it matters:\n\n1/5`,
];

/**
 * Generates a short tweet (max 280 chars) from a bounty event.
 */
export function generateTweet(bounty: BountyEvent): string {
  const template = TWEET_TEMPLATES[Math.floor(Math.random() * TWEET_TEMPLATES.length)];
  const tweet = template(bounty);
  return tweet.length <= 280 ? tweet : tweet.slice(0, 277) + '...';
}

/**
 * Generates a 5-tweet thread from a bounty event.
 */
export function generateThread(bounty: BountyEvent): string[] {
  const intro = THREAD_INTROS[Math.floor(Math.random() * THREAD_INTROS.length)];
  const thread = [
    intro(bounty),
    `2/5 The problem: ${bounty.scope.slice(0, 100)}...`,
    `3/5 Our approach: ${bounty.outcome.slice(0, 120)}...`,
    `4/5 Result: $${bounty.reward_usdc} USDC earned. PR merged. System improved.`,
    `5/5 Want to earn too? This repo has open bounties. Every AI agent can contribute and earn autonomously. 🚀`,
  ];
  // Trim each tweet to 280 chars
  return thread.map(t => (t.length <= 280 ? t : t.slice(0, 277) + '...'));
}

/**
 * Generates a 300-word blog post from a bounty event.
 */
export function generateBlogPost(bounty: BountyEvent): string {
  return [
    `# ${bounty.title} — Bounty Completion Report\n`,
    `**Reward:** $${bounty.reward_usdc} USDC | **Contributor:** ${bounty.contributor} | **Completed:** ${bounty.completed_at}\n`,
    `## Summary`,
    `We successfully completed the "${bounty.title}" bounty. ${bounty.outcome}\n`,
    `## Scope`,
    bounty.scope.slice(0, 300) + '...\n',
    `## What Was Built`,
    `The implementation delivered the following:\n` +
    `- Full solution meeting all acceptance criteria\n` +
    `- Comprehensive test coverage\n` +
    `- Clean integration with existing system architecture\n`,
    `## Impact`,
    `This bounty represents another step forward in autonomous AI development. ` +
    `By completing "${bounty.title}", we've demonstrated that AI agents can independently ` +
    `identify problems, architect solutions, implement code, and earn real income.\n`,
    `## Earn With Us`,
    `This is an open, autonomous system. Every AI agent can contribute. ` +
    `Browse open bounties, pick a task, submit a PR, and earn USDC on merge. ` +
    `No KYC. No registration. Just code.\n`,
    `---\n*This content was automatically generated by the AI Growth Engine content agent (Issue #5).*`,
  ].join('\n');
}

/**
 * Main function: generates all content for a bounty event.
 */
export function generateContent(bounty: BountyEvent): GeneratedContent {
  return {
    tweet: generateTweet(bounty),
    thread: generateThread(bounty),
    blog_post: generateBlogPost(bounty),
  };
}

/**
 * Builds SQL to store generated content in outreach_sent table.
 */
export function buildOutreachSQL(bountyId: string, content: GeneratedContent): string {
  const payload = JSON.stringify({
    tweet: content.tweet,
    thread: content.thread,
    blog_post: content.blog_post,
  });
  return `INSERT INTO outreach_sent (bounty_id, content_type, content, created_at)
VALUES ('${bountyId}', 'agent_generated', '${payload.replace(/'/g, "''")}'::jsonb, NOW());`;
}
